services:
  - type: web
    name: knowledge-process-api
    runtime: docker
    repo: https://github.com/RodeyManager/fastgpt-report
    branch: main
    rootDir: knowledge-process-api
    plan: free
    envVars:
      - key: PORT
        value: "8000"
